### ISSUE TITLE
[BUG]Dont collect some cards/quizzes

### ISSUE THREAD

**Issue by DerMuffin** [ATDavidson9/MicrosoftRewardsAutomaton#1]
At the end it says "unfinished quizez: 3"

Dont get it after 2 runs. Still the same. Thats the log:

CLI arguments: Namespace(drivers=[1, 2], numWords=50, headless=True, quiz_mode=True, debug=False)
Opening driver type: Device.PC
50 words selected from C:\Users\Username\Desktop\MicrosoftRewardsAutomaton-main\MicrosoftRewards\wordsList.txt
Search #1. URL: https://www.bing.com/search?q=repulsive
	
Search #2. URL: https://www.bing.com/search?q=memorise
	Learn a language. Memrise is authentic, useful & personalised.
Search #3. URL: https://www.bing.com/search?q=exclusive
	
Search #4. URL: https://www.bing.com/search?q=statement
	Duden | Statement | Rechtschreibung, Bedeutung, Definition ...
Search #5. URL: https://www.bing.com/search?q=type
Search #6. URL: https://www.bing.com/search?q=nose
	Nose - Wikipedia
Search #7. URL: https://www.bing.com/search?q=pen
	National Pen® bei pens.com - Sparen Sie bis zu 80%
Search #8. URL: https://www.bing.com/search?q=truculent
	Truculent Definition & Meaning - Merriam-Webster
Search #9. URL: https://www.bing.com/search?q=rule
	Rule Definition & Meaning - Merriam-Webster
Search #10. URL: https://www.bing.com/search?q=basket
	Basketbälle in großer Auswahl - Jetzt bei OTTO entdecken
Search #11. URL: https://www.bing.com/search?q=conscious
	
Search #12. URL: https://www.bing.com/search?q=four
	
Search #13. URL: https://www.bing.com/search?q=burn
	
Search #14. URL: https://www.bing.com/search?q=worthless
	
Search #15. URL: https://www.bing.com/search?q=crabby
	
Search #16. URL: https://www.bing.com/search?q=drain
	drain | Übersetzung Englisch-Deutsch - dict.cc
Search #17. URL: https://www.bing.com/search?q=ubiquitous
	
Search #18. URL: https://www.bing.com/search?q=plucky
	
Search #19. URL: https://www.bing.com/search?q=inquisitive
	Inquisitive Definition & Meaning - Merriam-Webster
Search #20. URL: https://www.bing.com/search?q=rat
	
Search #21. URL: https://www.bing.com/search?q=flashy
	
Search #22. URL: https://www.bing.com/search?q=chew
	
Search #23. URL: https://www.bing.com/search?q=hapless
	Hapless Definition & Meaning - Merriam-Webster
Search #24. URL: https://www.bing.com/search?q=river
	River (Fernsehserie) – Wikipedia
Search #25. URL: https://www.bing.com/search?q=stocking
	stocking anzeigen
Search #26. URL: https://www.bing.com/search?q=mint
	Home - Linux Mint
Search #27. URL: https://www.bing.com/search?q=uptight
	
Search #28. URL: https://www.bing.com/search?q=cobweb
	Cobweb - UK Cloud Solutions Provider, Microsoft CSP ...
Search #29. URL: https://www.bing.com/search?q=arch
	Startseite | ARCH+
Search #30. URL: https://www.bing.com/search?q=lick
	Lick – Wikipedia
Search #31. URL: https://www.bing.com/search?q=dinosaurs
	Dinosaur - Wikipedia
Search #32. URL: https://www.bing.com/search?q=dispensable
	
Search #33. URL: https://www.bing.com/search?q=kitty
	kiTTY | heise Download
Search #34. URL: https://www.bing.com/search?q=acidic
	
Search #35. URL: https://www.bing.com/search?q=political
	Political Definition & Meaning - Merriam-Webster
Search #36. URL: https://www.bing.com/search?q=whole
	
Search #37. URL: https://www.bing.com/search?q=abhorrent
	
Search #38. URL: https://www.bing.com/search?q=worm
	WORM – Wikipedia
Search #39. URL: https://www.bing.com/search?q=idea
	IDEA - KLAR. KONKRET. CHRISTLICH. : idea.de
Search #40. URL: https://www.bing.com/search?q=seal
	Seal – Wikipedia
Search #41. URL: https://www.bing.com/search?q=religion
	
Search #42. URL: https://www.bing.com/search?q=wretched
	
Search #43. URL: https://www.bing.com/search?q=fade
	Duden | fade | Rechtschreibung, Bedeutung, Definition ...
Search #44. URL: https://www.bing.com/search?q=remarkable
	Remarkable.com - reMarkable - The paper tablet
Search #45. URL: https://www.bing.com/search?q=beam
	Beam - YouTube
Search #46. URL: https://www.bing.com/search?q=fancy
	
Search #47. URL: https://www.bing.com/search?q=glamorous
	Glamorous - Women Clothing | Dresses for women, tops &amp ...
Search #48. URL: https://www.bing.com/search?q=insidious
	Ansehen – Insidious
Search #49. URL: https://www.bing.com/search?q=umbrella
	Rihanna - Umbrella (Orange Version) (Official Music Video ...
Search #50. URL: https://www.bing.com/search?q=upbeat
	Uppbeat – Copyright Free Music - Free For YouTubers & Creators
Attempting daily quizzes:
loading: https://rewards.microsoft.com/
Number of open offers: 4
Click Quiz identified.
Failed to complete quizzes: 
Traceback (most recent call last):
  File "C:\Users\Username\Desktop\MicrosoftRewardsAutomaton-main\MicrosoftRewards\SearchBingNews.py", line 118, in main
    iter_dailies(browser)
  File "C:\Users\Username\Desktop\MicrosoftRewardsAutomaton-main\MicrosoftRewards\MicrosoftDailies.py", line 90, in iter_dailies
    click_quiz(browser)
  File "C:\Users\Username\Desktop\MicrosoftRewardsAutomaton-main\MicrosoftRewards\MicrosoftDailies.py", line 175, in click_quiz
    random.choice(choices).click()
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: headless MicrosoftEdge=101.0.1210.32)
Stacktrace:
Backtrace:
	Microsoft::Applications::Events::EventProperties::unpack [0x009FC6D3+58355]
	Microsoft::Applications::Events::ISemanticContext::SetTicket [0x008DBBF1+1446177]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x006C351A+3162]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x006EDF64+103332]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x006E5BD8+69656]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0070134C+182156]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x006E5631+68209]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00701674+182964]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0070F163+239011]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x007010C6+181510]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x006E43B6+63478]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x006E5146+66950]
	Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00C016D5+640245]
	Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00B819D3+116723]
	Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00B81677+115863]
	Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00B856EA+132362]
	Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00B820BC+118492]
	Microsoft::Applications::Events::ISemanticContext::SetTicket [0x008EDBF7+1519911]
	Microsoft::Applications::Events::ISemanticContext::SetTicket [0x008F7C08+1560888]
	Microsoft::Applications::Events::ISemanticContext::SetTicket [0x008F7D92+1561282]
	Microsoft::Applications::Events::ISemanticContext::SetTicket [0x00909852+1633666]
	BaseThreadInitThunk [0x75C0FA29+25]
	RtlGetAppContainerNamedObjectPath [0x772D7A7E+286]
	RtlGetAppContainerNamedObjectPath [0x772D7A4E+238]

Querying for point totals:

----------------------------------------------------
PC points = 90/90
Mobile points = 60/60
Edge Bonus points = 12/12
Points earned today: 397
Total Points Available/Earned = 18088/94675
Number of incomplete quizzes: 3
----------------------------------------------------

Opening driver type: Device.Mobile
50 words selected from C:\Users\Username\Desktop\MicrosoftRewardsAutomaton-main\MicrosoftRewards\wordsList.txt
Search #1. URL: https://www.bing.com/search?q=smoggy
	Smoggy Definition & Meaning - Merriam-Webster
Search #2. URL: https://www.bing.com/search?q=hanging
	Hanging - Wikipedia
Search #3. URL: https://www.bing.com/search?q=beneficial
	Beneficial Definition & Meaning - Merriam-Webster
Search #4. URL: https://www.bing.com/search?q=color
	Farbe
Search #5. URL: https://www.bing.com/search?q=swing
	Swing (Musikrichtung) – Wikipedia
Search #6. URL: https://www.bing.com/search?q=pack
	Pack – Wikipedia
Search #7. URL: https://www.bing.com/search?q=cow
	COW – Wikipedia
Search #8. URL: https://www.bing.com/search?q=fit
	Fit
Search #9. URL: https://www.bing.com/search?q=blink
	blink anzeigen
Search #10. URL: https://www.bing.com/search?q=cattle
	Hausrind
Search #11. URL: https://www.bing.com/search?q=righteous
	
Search #12. URL: https://www.bing.com/search?q=wail
	Wail
Search #13. URL: https://www.bing.com/search?q=efficient
	Efficient Definition & Meaning - Merriam-Webster
Search #14. URL: https://www.bing.com/search?q=broken
	
Search #15. URL: https://www.bing.com/search?q=canvas
	Collaborate & Create Amazing Graphic Design for Free
Search #16. URL: https://www.bing.com/search?q=different
	
Search #17. URL: https://www.bing.com/search?q=double
	Double – Wikipedia
Search #18. URL: https://www.bing.com/search?q=peace
	Bilder von Peace
Search #19. URL: https://www.bing.com/search?q=tire
	Autoreifen
Search #20. URL: https://www.bing.com/search?q=nauseating
	
Search #21. URL: https://www.bing.com/search?q=market
	
Search #22. URL: https://www.bing.com/search?q=whine
	
Search #23. URL: https://www.bing.com/search?q=hole
	Hole
Search #24. URL: https://www.bing.com/search?q=hammer
	hammer anzeigen
Search #25. URL: https://www.bing.com/search?q=material
	WÖRTERBUCH
Search #26. URL: https://www.bing.com/search?q=numberless
	Numberless Definition & Meaning - Merriam-Webster
Search #27. URL: https://www.bing.com/search?q=malicious
	
Search #28. URL: https://www.bing.com/search?q=lowly
	
Search #29. URL: https://www.bing.com/search?q=steady
	Steady – People-Powered Media
Search #30. URL: https://www.bing.com/search?q=snakes
	Bilder von Snakes
Search #31. URL: https://www.bing.com/search?q=pump
	pump anzeigen
Search #32. URL: https://www.bing.com/search?q=grade
	Grade – Wikipedia
Search #33. URL: https://www.bing.com/search?q=quilt
	quilt anzeigen
Search #34. URL: https://www.bing.com/search?q=mixed
	MIXED - News zu VR, AR und KI
Search #35. URL: https://www.bing.com/search?q=wild
	WÖRTERBUCH
Search #36. URL: https://www.bing.com/search?q=excellent
	
Search #37. URL: https://www.bing.com/search?q=sisters
	Sisters
Search #38. URL: https://www.bing.com/search?q=planes
	Planes
Search #39. URL: https://www.bing.com/search?q=continue
	
Search #40. URL: https://www.bing.com/search?q=smooth
	
Search #41. URL: https://www.bing.com/search?q=correct
	
Search #42. URL: https://www.bing.com/search?q=load
	Load
Search #43. URL: https://www.bing.com/search?q=giraffe
	Giraffen
Search #44. URL: https://www.bing.com/search?q=tasteful
	
Search #45. URL: https://www.bing.com/search?q=obtain
Search #46. URL: https://www.bing.com/search?q=thinkable
	Home - thinkable
Search #47. URL: https://www.bing.com/search?q=knock
	Knock
Search #48. URL: https://www.bing.com/search?q=agreement
	WÖRTERBUCH
Search #49. URL: https://www.bing.com/search?q=farm
	WÖRTERBUCH
Search #50. URL: https://www.bing.com/search?q=utopian
	Utopian - definition of utopian by The Free Dictionary
Querying for point totals:

----------------------------------------------------
PC points = 90/90
Mobile points = 60/60
Edge Bonus points = 12/12
Points earned today: 397
Total Points Available/Earned = 18088/94675
Number of incomplete quizzes: 2
----------------------------------------------------

Max points achieved
We have reached the exit of the script after 00:06:24 h:m:s

@me if you need any information

**Comment by ATDavidson9** [comment]
The latest release should do a good job with the quizzes - there may be instances where it occasionally fails.

If you check your rewards you should see your daily set streak completed fairly consistently
