### ISSUE TITLE
KeyError: 'mobileSearch'

### ISSUE THREAD

**Issue by harminoff** [ATDavidson9/MicrosoftRewardsAutomaton#3]
Hi there. Getting the following error and having trouble figuring out whatt the issue is. I updated my useragent in driver.py however am still getting the error

> Max points not achieved -> retrying for device 2/3
Opening driver type: Device.Mobile
1 words selected from C:\Users\Administrator\Desktop\Bots\MicrosoftRewardsAutomaton-main\MicrosoftRewards\wordsList.txt
Search #1. URL: https://www.bing.com/search?q=crowded
        DICTIONARY
Querying for point totals:
Failed grabbing the points:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Bots\MicrosoftRewardsAutomaton-main\MicrosoftRewards\SearchBingNews.py", line 240, in get_point_total
    mobile_search = counters['mobileSearch'][0]
KeyError: 'mobileSearch'

**Comment by ATDavidson9** [comment]
That's interesting... do you get the mobile points when you look at microsoft rewards points breakdown?

Is this a consistent error?

**Comment by harminoff** [comment]
Yes it's consistent. I just tried a few searches on mobile and looked at the breakdown and I don't even have a mobile points section and the points for searching get allocated to PC searches.

This is what I show after doing 3 searches on my android, none on pc

https://i.imgur.com/4VSJfuY.png

**Comment by ATDavidson9** [comment]
You most likely are still a "Level 1" Rewards Point user. 

When you reach Level 2, it will unlock mobile points. Either that, or you may be in a region that doesn't support mobile points.

I've made a release that fixed the issue and wont throw an error if the mobileSearch key is missing
