### ISSUE TITLE
[Bug] Can init log and drivers folder on Mac OS

### ISSUE THREAD

**Issue by huukhanh** [ATDavidson9/MicrosoftRewardsAutomaton#4]
Environment: Mac M1
Python: 3.8
Command: `python MicrosoftRewards/SearchBingNews.py`
- FileNotFoundError: [Errno 2] No such file or directory: '[PATH]/MicrosoftRewardsAutomaton/MicrosoftRewards/logs/ms_rewards.log'
- FileNotFoundError: [Errno 2] No such file or directory: '[PATH]/MicrosoftRewardsAutomaton/MicrosoftRewards/drivers/edgedriver_mac64.zip'

**Comment by ATDavidson9** [comment]
Ill push up a fix later - but if you make folders named "logs" and "drivers" it will fix your issue

**Comment by huukhanh** [comment]
Thank you!!
